package com.epam.dao;

import java.util.List;
import java.util.stream.Collectors;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.epam.entity.Event;
import com.epam.storage.Storage;

public class EventDao {
    private static final Logger logger = LogManager.getLogger();
    private Storage storage;
    private long autogeneratedId = 1;

    public void setStorage(Storage storage) {
        this.storage = storage;
    }

    public Event getEventById(long eventId) {
        logger.info("Get Event By id from storage");
        return storage.getEventMap().get(eventId);
    }

    public List<Event> getEventsByTitle(String title, int pageSize, int pageNum) {
        logger.info("Get Events by title from storage with page size " + pageSize + " and page number" + pageNum);
        return storage.getEventMap().values().stream().filter(o -> o.getTitle()
                .contains(title)).skip((long) pageSize * (pageNum - 1)).limit(pageSize).collect(Collectors.toList());
    }

    public Event create(Event event) {
        event.setId(autogeneratedId);
        autogeneratedId++;
        logger.info("Put Event in storage. Event" + event);
        storage.getEventMap().put(event.getId(), event);
        return event;
    }

    public Event update(Event event) {
        logger.info("Update Event in storage. Event" + event);
        storage.getEventMap().put(event.getId(), event);
        return event;
    }

    public boolean delete(long eventId) {
        logger.info("Delete Event from storage. Event id" + eventId);
        Event event = storage.getEventMap().remove(eventId);
        return event != null;
    }
}
